# Generated by Django 2.1.5 on 2019-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_reply_commented_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_reply',
            name='is_read',
            field=models.IntegerField(default=0),
        ),
    ]
