# Generated by Django 2.1.5 on 2019-05-07 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_reply_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_reply',
            options={'ordering': ('-created',), 'verbose_name': ' 评论的评论 ', 'verbose_name_plural': ' 评论的评论 '},
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='body',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='reply_comment',
            field=models.IntegerField(default=0, verbose_name='评论评论的id'),
        ),
        migrations.AlterField(
            model_name='comment_reply',
            name='reply_type',
            field=models.IntegerField(default=0, verbose_name='回复0为主评论，1为子评论'),
        ),
    ]
