# Generated by Django 2.1.5 on 2019-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190507_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_reply',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
