# Generated by Django 2.2.5 on 2019-12-11 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0038_auto_20191211_1421'),
        ('comment', '0005_comment_reply_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightBlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('reported_text', models.TextField()),
                ('deleted_by_admin', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightblog_comment', to='article.LightBlogArticle')),
                ('comment_like', models.ManyToManyField(blank=True, related_name='comment_like', to=settings.AUTH_USER_MODEL)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='LightBlogComment_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_type', models.IntegerField(default=0, verbose_name='0 为主评论， 1为子评论')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_text', models.TextField()),
                ('reply_comment', models.IntegerField(default=0, verbose_name='评论 评论的id')),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_reported', models.BooleanField(default=False)),
                ('reported_text', models.TextField()),
                ('deleted_by_admin', models.BooleanField(default=False)),
                ('comment_like', models.ManyToManyField(blank=True, related_name='comment_reply_like', to=settings.AUTH_USER_MODEL)),
                ('comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightblogcomment_reply', to='comment.LightBlogComment')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
                ('commented_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment_reply',
        ),
    ]
