# Generated by Django 2.2.5 on 2019-12-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20191211_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightblogcomment_reply',
            options={'ordering': ('-created',)},
        ),
    ]
