# Generated by Django 2.2.5 on 2019-12-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20191212_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightblogcomment',
            name='reported_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lightblogcomment_reply',
            name='reported_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
