# Generated by Django 2.2.5 on 2019-12-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20191212_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightBlog_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, verbose_name=' 举报类型 ')),
                ('placeholder', models.CharField(max_length=200, verbose_name=' 举报placeholder ')),
            ],
        ),
        migrations.AddField(
            model_name='lightblogcomment',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_report', to='comment.LightBlog_report'),
        ),
        migrations.AddField(
            model_name='lightblogcomment_reply',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply_report', to='comment.LightBlog_report'),
        ),
    ]
