# Generated by Django 2.1.5 on 2019-04-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190423_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_read',
            field=models.IntegerField(default=0),
        ),
    ]
