# Generated by Django 2.1.5 on 2019-05-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190507_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=models.TextField(verbose_name=' 文章内容 '),
        ),
    ]
