# Generated by Django 2.1.5 on 2019-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190507_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='LightBlog niubility', max_length=50, null=True, verbose_name='图片标题')),
                ('image', models.ImageField(upload_to='Carousel', verbose_name='轮播图片')),
            ],
        ),
    ]
