# Generated by Django 2.1.5 on 2019-05-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': ' 轮播图 ', 'verbose_name_plural': ' 轮播图 '},
        ),
    ]
