# Generated by Django 2.1.5 on 2019-05-28 20:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20190528_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='image_preview',
            field=imagekit.models.fields.ProcessedImageField(default='default/default.jpg', upload_to='previewBlog', verbose_name='展示图片'),
        ),
    ]
