# Generated by Django 2.2.5 on 2019-10-11 12:32

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0017_articlepost_word_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightBlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' 文章标题 ')),
                ('article_status', models.IntegerField(default=1)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name=' 创建时间 ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name=' 更新时间 ')),
                ('article_body', models.TextField(verbose_name=' 文章内容 ')),
                ('article_wordCount', models.IntegerField(default=233, verbose_name=' 文章字数 ')),
                ('article_preview', imagekit.models.fields.ProcessedImageField(default='default/preview.jpg', upload_to=article.models.lightblog_articlepreview, verbose_name='展示图片')),
                ('article_descripton', models.CharField(max_length=30, verbose_name=' 文章简介 ')),
                ('isRecommend', models.BooleanField(default=False, verbose_name=' 是否推荐 ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightblog_article', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LightBlogSpecialColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_column', models.CharField(max_length=50, verbose_name=' 专栏名称 ')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name=' 创建时间 ')),
                ('description', models.CharField(max_length=100, verbose_name=' 专栏简介 ')),
                ('image_preview', imagekit.models.fields.ProcessedImageField(default='default/preview.jpg', upload_to=article.models.lightblog_specialcolumn, verbose_name='展示图片')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightblog_specialcolumn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LightBlogPersonalColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_column', models.CharField(max_length=20, verbose_name=' 个人栏目 ')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name=' 创建时间 ')),
                ('description', models.CharField(max_length=100, verbose_name=' 栏目简介 ')),
                ('image_preview', imagekit.models.fields.ProcessedImageField(default='default/preview.jpg', upload_to=article.models.lightblog_personalcolumn, verbose_name='展示图片')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightblog_personalcolumn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LightBlogArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_preview', imagekit.models.fields.ProcessedImageField(upload_to=article.models.lightblog_articleimgs, verbose_name='上传图片')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightblog_articleimage', to='article.LightBlogArticle')),
            ],
        ),
        migrations.AddField(
            model_name='lightblogarticle',
            name='personalColumn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_personalcolumn', to='article.LightBlogPersonalColumn'),
        ),
        migrations.AddField(
            model_name='lightblogarticle',
            name='specialColumn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_specialcolumn', to='article.LightBlogSpecialColumn'),
        ),
        migrations.AddField(
            model_name='lightblogarticle',
            name='users_dislike',
            field=models.ManyToManyField(blank=True, related_name='lightblog_users_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lightblogarticle',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='lightblog_users_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
