# Generated by Django 2.2.5 on 2019-10-15 10:01

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0018_auto_20191011_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightBlogSpecialTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_theme', models.CharField(max_length=50, verbose_name=' 专题名称 ')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name=' 创建时间 ')),
                ('description', models.CharField(max_length=100, verbose_name=' 专题简介 ')),
                ('image_preview', imagekit.models.fields.ProcessedImageField(default='default/preview.jpg', upload_to=article.models.lightblog_specialtheme, verbose_name='展示图片')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightblog_specialtheme', to=settings.AUTH_USER_MODEL)),
                ('special_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightblog_specialcolumn', to='article.LightBlogSpecialColumn')),
            ],
        ),
        migrations.AddField(
            model_name='lightblogarticle',
            name='specialTheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_specialtheme', to='article.LightBlogSpecialTheme'),
            preserve_default=False,
        ),
    ]
