# Generated by Django 2.2.5 on 2019-10-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20191015_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightblogspecialtheme',
            name='isPublish',
            field=models.IntegerField(default=0, verbose_name=' 是否发布 '),
        ),
    ]
