# Generated by Django 2.2.5 on 2019-10-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_lightblogspecialtheme_ispublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightblogspecialcolumn',
            name='isPublish',
            field=models.IntegerField(default=0, verbose_name=' 是否发布 '),
        ),
    ]
