# Generated by Django 2.2.5 on 2019-10-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_lightblogpersonalcolumn_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightblogarticle',
            name='article_status',
            field=models.IntegerField(default=0),
        ),
    ]
