# Generated by Django 2.2.5 on 2019-10-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20191017_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightblogarticle',
            name='article_descripton',
            field=models.CharField(max_length=200, verbose_name=' 文章简介 '),
        ),
    ]
