# Generated by Django 2.2.5 on 2019-10-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_auto_20191018_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lightblogarticle',
            options={'ordering': ('-updated',)},
        ),
        migrations.AlterModelOptions(
            name='lightblogpersonalcolumn',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='lightblogspecialcolumn',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='lightblogspecialtheme',
            options={'ordering': ('-created',)},
        ),
    ]
