# Generated by Django 2.2.5 on 2019-10-21 15:10

import article.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_lightblogarticleimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightblogarticleimage',
            name='image_preview',
            field=imagekit.models.fields.ProcessedImageField(upload_to=article.models.lightblog_articleimgspreview, verbose_name='上传图片'),
        ),
    ]
