# Generated by Django 2.2.5 on 2019-10-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_auto_20191021_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lightblogarticleimage',
            name='image_preview',
        ),
    ]
