# Generated by Django 2.2.5 on 2019-10-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_auto_20191021_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightBlogReplyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' 回复模板标题 ')),
                ('content', models.CharField(max_length=500, verbose_name=' 回复模板内容 ')),
            ],
        ),
    ]
