# Generated by Django 2.2.5 on 2019-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_lightblogreplytemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightblogarticle',
            name='checkText',
            field=models.CharField(default='', max_length=300, verbose_name=' 审核内容 '),
        ),
    ]
