# Generated by Django 2.2.5 on 2019-10-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0033_lightblogarticle_checktext'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightblogarticle',
            name='checkTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name=' 审核时间 '),
        ),
    ]
