# Generated by Django 2.2.5 on 2019-11-28 15:17

import article.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_lightblogspecialcolumn_isrecommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightBlogBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' banner 标题 ')),
                ('desc', models.CharField(max_length=200, verbose_name=' banner 介绍 ')),
                ('url', models.CharField(max_length=300, verbose_name=' banner Url ')),
                ('image', imagekit.models.fields.ProcessedImageField(default='default/author-bg.jpg', upload_to=article.models.lightblog_banner, verbose_name='Banner')),
            ],
        ),
    ]
