# Generated by Django 2.2.5 on 2019-11-28 15:28

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0036_lightblogbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightblogbanner',
            name='image',
            field=models.ImageField(default='default/author-bg.jpg', upload_to=article.models.lightblog_banner),
        ),
    ]
