# Generated by Django 2.2.5 on 2019-12-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0037_auto_20191128_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentator',
        ),
    ]
