# Generated by Django 2.2.5 on 2019-12-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20191211_1421'),
        ('article', '0038_auto_20191211_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
