# Generated by Django 3.0.3 on 2020-02-28 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0039_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightblogarticle',
            name='collector',
            field=models.ManyToManyField(blank=True, related_name='lightblog_collector', to=settings.AUTH_USER_MODEL),
        ),
    ]
