# Generated by Django 2.1.5 on 2019-03-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='aboutme',
            field=models.TextField(blank=True, verbose_name=' 自我介绍 '),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name=' 地址 '),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name=' 在职公职 '),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=100, verbose_name=' 工作 '),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='school',
            field=models.CharField(blank=True, max_length=100, verbose_name=' 学校 '),
        ),
    ]
