# Generated by Django 2.1.5 on 2019-05-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190320_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': ' 用户信息 ', 'verbose_name_plural': ' 用户信息 '},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name=' 头像 '),
        ),
    ]
