# Generated by Django 2.1.5 on 2019-05-27 18:24

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190527_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avator', verbose_name='展示图片'),
        ),
    ]
