# Generated by Django 2.1.5 on 2019-05-28 20:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190527_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default='default/default.jpg', upload_to='avator', verbose_name='展示图片'),
        ),
    ]
