# Generated by Django 2.2.5 on 2019-11-25 15:12

import account.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_bg',
            field=imagekit.models.fields.ProcessedImageField(default='default/author-bg.jpg', upload_to=account.models.lightblog_authorbg, verbose_name='展示图片'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default='default/default.jpg', upload_to=account.models.lightblog_authorbg, verbose_name='展示图片'),
        ),
    ]
