# Generated by Django 2.2.5 on 2019-12-04 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_auto_20191125_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_follow',
            field=models.ManyToManyField(blank=True, related_name='user_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
